TENSION_PRIMARY_R2_MIN = 0.96
TENSION_WINDOW_STEP = 50
TENSION_THRESHOLD_STRESS = 1.24e6
TENSION_STRESS_GATE_DELTA = 1.0e6
TENSION_ZERO_STRAIN_MAX = 0.035
TENSION_SLOPE_CV_MAX = 0.40
PETG_TENSION_RECOVERY_WINDOW_MIN = 20
PETG_TENSION_RECOVERY_WINDOW_STEP = 5
PETG_TENSION_FALLBACK_MIN_POINTS = 10
PETG_TENSION_RECOVERY_MIN_START_DELTA = 0.005
PETG_TENSION_BRITTLE_START_TOLERANCE = 0.002
PETG_TENSION_PROOF_ZERO_STRAIN_MAX = 0.01
PETG_TENSION_PHYSICAL_OVERRIDE_SLOPE_RATIO_MIN = 0.5
PETG_TENSION_PHYSICAL_OVERRIDE_SLOPE_RATIO_MAX = 1.5
PETG_TENSION_MEANINGFUL_PROOF_GAP = 0.01

FIT_MODE_PETG_SHORT_WINDOW_RECOVERY = "petg_short_window_recovery"
DECISION_ACCEPTED_PETG_RECOVERY = "accepted_petg_short_window_recovery"
DECISION_ACCEPTED_PETG_PHYSICAL_OVERRIDE = "accepted_petg_physical_override"

TENSION_YIELD_METHOD_PROOF = "proof_stress"
TENSION_YIELD_METHOD_FIRST_MAX = "first_max"
TENSION_YIELD_METHOD_LOCAL_PEAK = "local_peak"

EXPECTED_SAMPLE_SKIP_MARKERS = (
    "marked as failed (F)",
    "was not found in column 'Sample Name'",
    "missing 'Avg. L Pre' or 'Pre Cross sectional area'",
)
