from shared_core.adaptive_fit import SUBGROUP_FALLBACK_RELATIVE_BAND, SUBGROUP_MODIFIED_ZSCORE_MAX


COMPRESSION_PRIMARY_R2_MIN = 0.995
COMPRESSION_CANDIDATE_WINDOW_MIN = 20
COMPRESSION_CANDIDATE_WINDOW_MAX = None
COMPRESSION_CANDIDATE_WINDOW_STEP = 5
COMPRESSION_SHORT_RAMP_WINDOW_MIN = 8
COMPRESSION_SHORT_RAMP_WINDOW_MAX = 18
COMPRESSION_SHORT_RAMP_WINDOW_STEP = 1
COMPRESSION_SHORT_RAMP_R2_MIN = 0.998
COMPRESSION_SHORT_RAMP_SLOPE_CV_MAX = 0.08
COMPRESSION_SHORT_RAMP_ZERO_STRAIN_MAX = 0.005
COMPRESSION_SHORT_RAMP_RELAXED_WINDOW_MIN = 9
COMPRESSION_SHORT_RAMP_RELAXED_WINDOW_MAX = 14
COMPRESSION_SHORT_RAMP_RELAXED_WINDOW_STEP = 1
COMPRESSION_SHORT_RAMP_RELAXED_R2_MIN = 0.995
COMPRESSION_SHORT_RAMP_RELAXED_SLOPE_CV_MAX = 0.10
COMPRESSION_SHORT_RAMP_RELAXED_ZERO_STRAIN_MAX = 0.005
COMPRESSION_SHORT_RAMP_PRE_YIELD_STRAIN_MAX = 0.04
COMPRESSION_SHORT_RAMP_USABLE_POINTS_MAX = 40
COMPRESSION_ZERO_STRAIN_MAX = 0.02
COMPRESSION_ZERO_STRAIN_NEAR_ORIGIN_MAX = 0.001
COMPRESSION_SLOPE_CV_MAX = 0.35
COMPRESSION_STARTUP_SKIP_FRACTION = 0.45
COMPRESSION_STARTUP_SKIP_STRAIN_MAX = 0.05
COMPRESSION_SOFTENING_WINDOW = 11
COMPRESSION_SOFTENING_DROP_RATIO = 0.85
COMPRESSION_SOFTENING_CONSECUTIVE = 3
COMPRESSION_GEOMETRIC_REHARDENING_RATIO = 0.90
COMPRESSION_SOFTENING_START_STRESS_RATIO = 0.05
COMPRESSION_WINDUP_WINDOW = 11
COMPRESSION_WINDUP_TARGET_RATIO = 0.70
COMPRESSION_WINDUP_CV_MAX = 0.12
COMPRESSION_WINDUP_CONSECUTIVE = 3
COMPRESSION_SUBGROUP_MODIFIED_ZSCORE_MAX = SUBGROUP_MODIFIED_ZSCORE_MAX
COMPRESSION_SUBGROUP_FALLBACK_RELATIVE_BAND = SUBGROUP_FALLBACK_RELATIVE_BAND
COMPRESSION_PROOF_STRAIN_OFFSET = 0.002

YIELD_METHOD_SOFTENING = "softening_knee"
YIELD_METHOD_FIRST_MAX = "first_local_maximum"
YIELD_METHOD_PROOF = "proof_stress"

FIT_MODE_DIRECT = "direct"
FIT_MODE_NOISE_TRIMMED = "noise_trimmed"
FIT_MODE_PRE_YIELD_CLIPPED = "pre_yield_clipped"
FIT_MODE_SHORT_RAMP_EXCEPTION = "short_ramp_exception"
FIT_MODE_SHORT_RAMP_RELAXED = "short_ramp_relaxed"
FIT_MODE_ALTERNATE = "alternate_candidate"
FIT_MODE_MANUAL_EXCEPTION = "manual_exception"

DECISION_ACCEPTED_CLUSTERED = "accepted_clustered"
DECISION_ACCEPTED_CORRECTED = "accepted_corrected"
DECISION_ACCEPTED_EXCEPTION = "accepted_manual_exception"
DECISION_REJECTED_NO_FIT = "rejected_no_pre_yield_fit"
DECISION_REJECTED_GEOMETRIC = "rejected_geometric_instability"
DECISION_REJECTED_OUTLIER = "rejected_sibling_outlier"

COMPRESSION_MANUAL_FIT_WINDOWS = {
    # User-approved one-off recovery for the short elastic rise in this sample.
    "P0CP70W - 3": (0.003459, 0.011533),
    # User-approved recovery for a valid but subgroup-high elastic segment.
    "P1CP70S - 2": (0.005157, 0.021778),
    # User-approved recovery for a noisy short-ramp sample that misses automated thresholds.
    "P1CP70W - 1": (0.002321, 0.017417),
}

COMPRESSION_MANUAL_ACCEPT_TOP_CANDIDATES = {
    # User-approved recovery: keep the extracted fit and ignore the sibling-band rejection.
    "P1CP60S - 3",
}
