SHEAR_WINDOW_MIN = 18
SHEAR_WINDOW_STEP = 25
SHEAR_FALLBACK_MIN_POINTS = 18

SHEAR_PRIMARY_R2_MIN = 0.95
SHEAR_THRESHOLD_STRESS = 0.8e6
SHEAR_STRESS_GATE_DELTA = 1.0e6
SHEAR_ZERO_STRAIN_MAX = 0.035
SHEAR_SLOPE_CV_MAX = 0.40
SHEAR_SUBGROUP_RELATIVE_BAND = 0.30

SHEAR_DROP_RATIO = 0.35
SHEAR_DROP_ABS = 1.0e6

EXPECTED_SAMPLE_SKIP_MARKERS = (
    "marked as failed (F)",
    "was not found in column 'Sample Name'",
    "missing 'Avg. L Pre' or 'Pre Cross sectional area'",
)
